package com.br.painelmobile.modelo.persistencia.entidade.mapeadas;



import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.NamedNativeQuery;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



@NamedNativeQuery(name="postagemComCategoria", 
	query=" SELECT" + 
			"       wp_posts.id As idPostagem," + 
			"       wp_posts.post_title as titulo," + 
			"       wp_posts.guid as linkDaPostagem," +
			"       wp_posts.post_content as conteudo," + 
			"       wp_terms.name AS categoria" + 		
			"    FROM" + 
			"        wp_posts" + 
			"    INNER JOIN" + 
			"        wp_term_relationships" + 
			"            ON (" + 
			"                wp_posts.ID = wp_term_relationships.object_id" + 
			"            )" + 
			"    INNER JOIN" + 
			"        wp_term_taxonomy" + 
			"            ON (" + 
			"                wp_term_relationships.term_taxonomy_id = wp_term_taxonomy.term_taxonomy_id" + 
			"            )" + 
			"    INNER JOIN" + 
			"          wp_terms" + 
			"            ON (" + 
			"                wp_terms.term_id = wp_term_taxonomy.term_id" + 
			"             )" + 
			"" + 
			"    WHERE" + 			 
			"       wp_posts.post_status = 'publish' " + 
			"        AND wp_posts.post_type = 'post' " + 
			"        AND wp_term_taxonomy.taxonomy = 'category' " + 
			"        AND wp_terms.Term_id = 42 " +
			"       ORDER BY" + 
			"        post_date DESC limit 6" ,
	resultSetMapping="postagemComCategoriaMapping"		
		)

@SqlResultSetMapping(name="postagemComCategoriaMapping",
	classes= {
			@ConstructorResult(
					targetClass=PostagemComCategoria.class,
					columns= {
							@ColumnResult(name="idPostagem",  type=Integer.class),
							@ColumnResult(name="titulo", type=byte[].class ),
							@ColumnResult(name="linkDaPostagem" ),
							@ColumnResult(name="conteudo", type=byte[].class),
							@ColumnResult(name="categoria")
					}
			)
	}

)




/**
 * Postagem generated by hbm2java
 */
@Entity
@Table(name="wp_posts", catalog="portalsescam")
@AttributeOverride(name="id", column=@Column(name="id"))
public class Postagem extends ValueObject implements Serializable {


	private static final long serialVersionUID = 3808598493314726421L;
	
	
	private long postAuthor;
	private Date postDate;
	private Date postDateGmt;
	private byte[] postContent;
	private byte[] postTitle;
	private String postExcerpt;
	private String postStatus;
	private String commentStatus;
	private String pingStatus;
	private String postPassword;
	private String postName;
	private String toPing;
	private String pinged;
	private Date postModified;
	private Date postModifiedGmt;
	private String postContentFiltered;
	private long postParent;
	private String guid;
	private int menuOrder;
	private String postType;
	private String postMimeType;
	private long commentCount;


	public Postagem() {
	}


	public Postagem(long postAuthor, Date postDate, Date postDateGmt, byte[] postContent,
			byte[] postTitle, String postExcerpt, String postStatus, String commentStatus,
			String pingStatus, String postPassword, String postName, String toPing, String pinged,
			Date postModified, Date postModifiedGmt, String postContentFiltered, long postParent,
			String guid, int menuOrder, String postType, String postMimeType, long commentCount) {
		this.postAuthor = postAuthor;
		this.postDate = postDate;
		this.postDateGmt = postDateGmt;
		this.postContent = postContent;
		this.postTitle = postTitle;
		this.postExcerpt = postExcerpt;
		this.postStatus = postStatus;
		this.commentStatus = commentStatus;
		this.pingStatus = pingStatus;
		this.postPassword = postPassword;
		this.postName = postName;
		this.toPing = toPing;
		this.pinged = pinged;
		this.postModified = postModified;
		this.postModifiedGmt = postModifiedGmt;
		this.postContentFiltered = postContentFiltered;
		this.postParent = postParent;
		this.guid = guid;
		this.menuOrder = menuOrder;
		this.postType = postType;
		this.postMimeType = postMimeType;
		this.commentCount = commentCount;
	}


	

	@Column(name = "post_author", nullable = false)
	public long getPostAuthor() {
		return this.postAuthor;
	}


	public void setPostAuthor(long postAuthor) {
		this.postAuthor = postAuthor;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_date", nullable = false, length = 19)
	public Date getPostDate() {
		return this.postDate;
	}


	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_date_gmt", nullable = false, length = 19)
	public Date getPostDateGmt() {
		return this.postDateGmt;
	}


	public void setPostDateGmt(Date postDateGmt) {
		this.postDateGmt = postDateGmt;
	}


	@Column(name = "post_content", nullable = false)
	public byte[] getPostContent() {
		return this.postContent;
	}


	public void setPostContent(byte[] postContent) {
		this.postContent = postContent;
	}


	@Column(name = "post_title", nullable = false, length = 65535)
	public byte[] getPostTitle() {
		return this.postTitle;
	}


	public void setPostTitle(byte[] postTitle) {
		this.postTitle = postTitle;
	}


	@Column(name = "post_excerpt", nullable = false, length = 65535)
	public String getPostExcerpt() {
		return this.postExcerpt;
	}


	public void setPostExcerpt(String postExcerpt) {
		this.postExcerpt = postExcerpt;
	}


	@Column(name = "post_status", nullable = false, length = 20)
	public String getPostStatus() {
		return this.postStatus;
	}


	public void setPostStatus(String postStatus) {
		this.postStatus = postStatus;
	}


	@Column(name = "comment_status", nullable = false, length = 20)
	public String getCommentStatus() {
		return this.commentStatus;
	}


	public void setCommentStatus(String commentStatus) {
		this.commentStatus = commentStatus;
	}


	@Column(name = "ping_status", nullable = false, length = 20)
	public String getPingStatus() {
		return this.pingStatus;
	}


	public void setPingStatus(String pingStatus) {
		this.pingStatus = pingStatus;
	}


	@Column(name = "post_password", nullable = false, length = 20)
	public String getPostPassword() {
		return this.postPassword;
	}


	public void setPostPassword(String postPassword) {
		this.postPassword = postPassword;
	}


	@Column(name = "post_name", nullable = false, length = 200)
	public String getPostName() {
		return this.postName;
	}


	public void setPostName(String postName) {
		this.postName = postName;
	}


	@Column(name = "to_ping", nullable = false, length = 65535)
	public String getToPing() {
		return this.toPing;
	}


	public void setToPing(String toPing) {
		this.toPing = toPing;
	}


	@Column(name = "pinged", nullable = false, length = 65535)
	public String getPinged() {
		return this.pinged;
	}


	public void setPinged(String pinged) {
		this.pinged = pinged;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_modified", nullable = false, length = 19)
	public Date getPostModified() {
		return this.postModified;
	}


	public void setPostModified(Date postModified) {
		this.postModified = postModified;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_modified_gmt", nullable = false, length = 19)
	public Date getPostModifiedGmt() {
		return this.postModifiedGmt;
	}


	public void setPostModifiedGmt(Date postModifiedGmt) {
		this.postModifiedGmt = postModifiedGmt;
	}


	@Column(name = "post_content_filtered", nullable = false)
	public String getPostContentFiltered() {
		return this.postContentFiltered;
	}


	public void setPostContentFiltered(String postContentFiltered) {
		this.postContentFiltered = postContentFiltered;
	}


	@Column(name = "post_parent", nullable = false)
	public long getPostParent() {
		return this.postParent;
	}


	public void setPostParent(long postParent) {
		this.postParent = postParent;
	}


	@Column(name = "guid", nullable = false)
	public String getGuid() {
		return this.guid;
	}


	public void setGuid(String guid) {
		this.guid = guid;
	}


	@Column(name = "menu_order", nullable = false)
	public int getMenuOrder() {
		return this.menuOrder;
	}


	public void setMenuOrder(int menuOrder) {
		this.menuOrder = menuOrder;
	}


	@Column(name = "post_type", nullable = false, length = 20)
	public String getPostType() {
		return this.postType;
	}


	public void setPostType(String postType) {
		this.postType = postType;
	}


	@Column(name = "post_mime_type", nullable = false, length = 100)
	public String getPostMimeType() {
		return this.postMimeType;
	}


	public void setPostMimeType(String postMimeType) {
		this.postMimeType = postMimeType;
	}


	@Column(name = "comment_count", nullable = false)
	public long getCommentCount() {
		return this.commentCount;
	}


	public void setCommentCount(long commentCount) {
		this.commentCount = commentCount;
	}

	
	
	
}
